### ISSUE TITLE
关于 java 热更新的请教

### ISSUE THREAD

**Issue by tcsecchen** [landon30/Bulls#1]
您好，我看了您的博客里关于spring-loaded、JRebel以及自定义classloader实现热更新的文章
不过我现在有点小问题，这些技术是否可以实现  java系统类的热替换（例如java.lang.String）
目前我是使用了 Aspectj 对 java 的 rt.jar 中的一些类进行了改写，现在我想热更新rt.jar
因为rt.jar 是由 BootStrapClassloader加载的， 我不知道该怎么去 热替换
谢谢您的博客对我的帮助

**Comment by landon30** [comment]
你好。Java除了ClassLoader实现热更以外，还有一种叫redefine的方式，即重定义。可以参考java.lang.instrument.Instrumentation接口相关实现

**Comment by tcsecchen** [comment]
spring-loaded 通过 watchJars 可以 检测 jar包的更新，但是目前我测试时 由 -Xbootclasspath 引进的jar包好像替换没什么作用。
redefine的话我是用 agentmain 调用 inst.redefineClasses 做的，但是这个我不知道怎么热更新jar包，把jar包中所有的类都redefine吗？
多谢您的帮助！

**Comment by landon30** [comment]
1. 因为rt.jar就是在-Xbootclasspath，默认就是BootStrapClassLoader加载的，即优先被启动类加载器加载了
2. 将热更的类打成jar包，写一个解析类解析jar，依次redefine即可
